import moment from "moment";
export const fakeDataEvent = [
  {
    id: 1,
    title: "Turno Juan Carlos",
    start: moment("11-22-2022 00:00:00").toDate(),
    end: moment("11-22-2022 8:00:00").toDate(),
    branchId: 1,
    guardId: 1,
    nota: "Cubrir Puesto de trabajo",
    guard: {
      id: 1,
      name: "Juan Carlos",
      lastname: "Lopez",
      CUIL: 1231232,
      Provincia: "Buenos Aires",
      Localidad: "Mar del Plata",
    },
  },
  {
    id: 2,
    title: "Turno Juan Bautista",
    start: moment("11-26-22 08:00:00").toDate(),
    end: moment("11-26-22 16:00:00").toDate(),
    branchId: 1,
    guardId: 3,
    nota: "Cubrir Puesto de trabajo",
    guard: {
      id: 3,
      name: "Juan Bautista",
      lastname: "Alberdi",
      CUIL: 1231232,
      Provincia: "Buenos Aires",
      Localidad: "Mar del Plata",
    },
  },
  {
    id: 3,
    title: "Turno Esteban Echeverria",
    start: moment("11-30-22 16:00:00").toDate(),
    end: moment("11-30-22 00:0:00").toDate(),
    branchId: 1,
    guardId: 4,
    nota: "Cubrir Puesto de trabajo",
    guard: {
      id: 4,
      name: "Esteban",
      lastname: "Echeverria",
      CUIL: 1231232,
      Provincia: "Buenos Aires",
      Localidad: "Mar del Plata",
    },
  },
];
