const { Guard } = require("../../models");

const guards = [
  {
    name: "Antonio",
    lastname: "López",
    email: "antonio@guard.com",
    cuil: 20058916332,
    password: "123456",
    street: "San Martin",
    number: 587,
    city: "Rosario",
    province: "Santa Fe",
    postalcode: "S2000",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Juan",
    lastname: "Fernandez",
    email: "juan@guard.com",
    cuil: 20168917452,
    password: "123456",
    street: "Gallo",
    number: 1570,
    city: "CABA",
    province: "Ciudad Autonoma de Buenos Aires",
    postalcode: "C1425",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Martin",
    lastname: "Martinez",
    email: "martin@guard.com",
    cuil: 27254584242,
    password: "123456",
    street: "Ituzaingó",
    number: 232,
    city: "Lujan",
    province: "Buenos Aires",
    postalcode: "B6700",
    active: false,
    first_access: false,
    clientId: 2,
  },
  {
    name: "Carolina",
    lastname: "Alvarez",
    email: "carolina@guard.com",
    cuil: 23304565643,
    password: "123456",
    street: "Viamonte",
    number: 3450,
    city: "Rosario",
    province: "Santa Fe",
    postalcode: "S2003",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Anibal",
    lastname: "Bianchi",
    email: "anibalbianchi@guard.com",
    cuil: 20342678265,
    password: "123456",
    street: "Ignacio Warnes",
    number: 1352,
    city: "Rosario",
    province: "Santa Fe",
    postalcode: "S2005",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Mario",
    lastname: "Casero",
    email: "mariocasero@guard.com",
    cuil: 20302134555,
    password: "123456",
    street: "Galvez",
    number: 879,
    city: "Rosario",
    province: "Santa Fe",
    postalcode: "S2001",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Juana",
    lastname: "Salvatori",
    email: "juana@guard.com",
    cuil: 27271242233,
    password: "123456",
    street: "San Lorenzo",
    number: 6499,
    city: "Santa Fe",
    province: "Santa Fe",
    postalcode: "S3000",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Bautista",
    lastname: "Romero",
    email: "bautista@guard.com",
    cuil: 20334241585,
    password: "123456",
    street: "Alberti",
    number: 2743,
    city: "Santa Fe",
    province: "Santa Fe",
    postalcode: "S3004",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Santiago",
    lastname: "Campos",
    email: "santiagocampos@guard.com",
    cuil: 20334201585,
    password: "123456",
    street: "Corrientes",
    number: 2870,
    city: "Santa Fe",
    province: "Santa Fe",
    postalcode: "S3000",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Ramiro",
    lastname: "Martinez",
    email: "ramiro@guard.com",
    cuil: 20293693365,
    password: "123456",
    street: "Zañartu",
    number: 848,
    city: "CABA",
    province: "Ciudad Autonoma de Buenos Aires",
    postalcode: "C1424",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Clara",
    lastname: "Bustamante",
    email: "clara@guard.com",
    cuil: 27352058303,
    password: "123456",
    street: "Patron",
    number: 7197,
    city: "CABA",
    province: "Ciudad Autonoma de Buenos Aires",
    postalcode: "C1408",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Mariano",
    lastname: "Montero",
    email: "mariano@guard.com",
    cuil: 20340254265,
    password: "123456",
    street: "Esteban Merlo",
    number: 4644,
    city: "Caseros",
    province: "Provincia de Buenos Aires",
    postalcode: "B1678",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Carlos",
    lastname: "Astas",
    email: "carlosastas@guard.com",
    cuil: 20278408995,
    password: "123456",
    street: "Planes",
    number: 1141,
    city: "CABA",
    province: "Ciudad Autonoma de Buenos Aires",
    postalcode: "C1405",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Mariana",
    lastname: "Diaz",
    email: "marianadiaz@guard.com",
    cuil: 27361200233,
    password: "123456",
    street: "Carlos Villate",
    number: 2371,
    city: "Olivos",
    province: "Provincia de Buenos Aires",
    postalcode: "B1636",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Agustin",
    lastname: "Sarria",
    email: "agustinsarria@guard.com",
    cuil: 20381251563,
    password: "123456",
    street: "Esteban Merlo",
    number: 4828,
    city: "Caseros",
    province: "Provincia de Buenos Aires",
    postalcode: "B1678",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Camilo",
    lastname: "Ritondo",
    email: "camilo@guard.com",
    cuil: 20402565203,
    password: "123456",
    street: "Suipacha",
    number: 670,
    city: "Haedo",
    province: "Provincia de Buenos Aires",
    postalcode: "B1706",
    first_access: false,
    clientId: 2,
  },
  {
    name: "Facundo",
    lastname: "Tassi",
    email: "facundo@guard.com",
    cuil: 23345896784,
    password: "123456",
    street: "Eva Perón",
    number: 2102,
    city: "Villa Gobernador Gálvez",
    province: "Santa Fe",
    postalcode: "S2124",
    first_access: false,
    clientId: 2,
  },
  // {
  //   name: "Lionel",
  //   lastname: "Messi",
  //   email: "messi@guard.com",
  //   cuil: 23345896554,
  //   password: "123456",
  //   street: "Balcarce",
  //   number: 1222,
  //   city: "San Nicolas",
  //   province: "Buenos Aires",
  //   postalcode: "B2900",
  //   first_access: false,
  //   clientId: 2,
  // },
];

async function createGuards() {
  for (let i = 0; i < guards.length; i++) {
    let guard = guards[i];
    await Guard.create(guard);
  }
  console.log("GUARDS created ok");
}

module.exports = createGuards;
